//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WidgetProvider.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WidgetProvider.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk transfer rate.
        /// </summary>
        internal static string DiskRwActivityTemplate_DiskTransferRate {
            get {
                return ResourceManager.GetString("DiskRwActivityTemplate_DiskTransferRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        internal static string DiskRwActivityTemplate_Read {
            get {
                return ResourceManager.GetString("DiskRwActivityTemplate_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write.
        /// </summary>
        internal static string DiskRwActivityTemplate_Write {
            get {
                return ResourceManager.GetString("DiskRwActivityTemplate_Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Time.
        /// </summary>
        internal static string DiskTimeActivityTemplate_ActiveTime {
            get {
                return ResourceManager.GetString("DiskTimeActivityTemplate_ActiveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average transfer time.
        /// </summary>
        internal static string DiskTimeActivityTemplate_AvgTransferTime {
            get {
                return ResourceManager.GetString("DiskTimeActivityTemplate_AvgTransferTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive.
        /// </summary>
        internal static string NetworkActivityTemplate_Recv {
            get {
                return ResourceManager.GetString("NetworkActivityTemplate_Recv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string NetworkActivityTemplate_Sent {
            get {
                return ResourceManager.GetString("NetworkActivityTemplate_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoughput.
        /// </summary>
        internal static string NetworkActivityTemplate_Throughput {
            get {
                return ResourceManager.GetString("NetworkActivityTemplate_Throughput", resourceCulture);
            }
        }
    }
}
